name: Frontend Image

on:
  push:
    branches: ["main"]
    paths:
      - "frontend/**"
  workflow_dispatch: {}

permissions:
  contents: write
  packages: write

jobs:
  build-and-push:
    if: ${{ github.actor != 'github-actions[bot]' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Compute image metadata
        id: vars
        shell: bash
        run: |
          OWNER_LC=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          REPO_LC=$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')
          IMAGE="ghcr.io/${OWNER_LC}/${REPO_LC}-frontend"
          TAG="${GITHUB_SHA}"
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "Resolved IMAGE=$IMAGE, TAG=$TAG"

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm ci
        working-directory: frontend

      - name: Run tests
        run: npm test -- --watch=false --passWithNoTests
        working-directory: frontend

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        shell: bash
        working-directory: frontend
        run: |
          docker build -t "$IMAGE:$TAG" -t "$IMAGE:latest" .
          docker push "$IMAGE:$TAG"
          docker push "$IMAGE:latest"

      - name: Persist image tag
        shell: bash
        run: |
          echo "$TAG" > frontend/image-tag.txt
          if git diff --quiet --exit-code -- frontend/image-tag.txt; then
            echo "Image tag unchanged; skipping commit update."
            exit 0
          fi
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add frontend/image-tag.txt
          git commit -m "chore(frontend): update image tag $TAG"
          git push
