name: Frontend Image

on:
  push:
    branches: ["main"]
    # 메인 브랜치에 변경이 생기면 프론트 이미지 빌드/배포 실행
  workflow_dispatch: {}

permissions:
  contents: write
  packages: write

jobs:
  build-and-push:
    if: ${{ github.actor != 'github-actions[bot]' }}
    # Actions 봇이 만든 커밋에 의해 반복 실행되는 것을 차단
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        # 전체 히스토리 확보 (태그 기록 반영 시 필요)

      - name: Determine project layout
        id: layout
        shell: bash
        run: |
          if [ -f frontend/package.json ]; then
            echo "project_dir=frontend" >> "$GITHUB_OUTPUT"
            echo "image_suffix=-frontend" >> "$GITHUB_OUTPUT"
          else
            echo "project_dir=." >> "$GITHUB_OUTPUT"
            echo "image_suffix=" >> "$GITHUB_OUTPUT"
          fi
        # frontend 폴더 존재 여부에 따라 경로/이미지 접미사 결정

      - name: Compute image metadata
        id: vars
        shell: bash
        run: |
          OWNER_LC=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          REPO_LC=$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')
          SUFFIX="${{ steps.layout.outputs.image_suffix }}"
          IMAGE="ghcr.io/${OWNER_LC}/${REPO_LC}${SUFFIX}"
          TAG="${GITHUB_SHA}"
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "Resolved IMAGE=$IMAGE, TAG=$TAG"
        # GHCR 이미지 이름과 태그(SHA)를 계산해 환경 변수로 등록

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
        # Node 18 환경 준비 및 npm 캐시 활성화

      - name: Install dependencies
        run: npm ci
        working-directory: ${{ steps.layout.outputs.project_dir }}
        # package-lock 기반으로 의존성 설치

      - name: Run tests
        run: npm test -- --watch=false --passWithNoTests
        working-directory: ${{ steps.layout.outputs.project_dir }}
        # 유닛 테스트 실행 (없으면 통과 처리)

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
        # GHCR 레지스트리에 로그인

      - name: Build and push image
        shell: bash
        working-directory: ${{ steps.layout.outputs.project_dir }}
        run: |
          docker build -t "$IMAGE:$TAG" -t "$IMAGE:latest" .
          docker push "$IMAGE:$TAG"
          docker push "$IMAGE:latest"
        # 프론트엔드 Docker 이미지 빌드 후 푸시

      - name: Persist image tag
        shell: bash
        run: |
          TARGET_DIR="${{ steps.layout.outputs.project_dir }}"
          if [ "$TARGET_DIR" = "." ]; then
            TARGET_FILE="image-tag.txt"
          else
            TARGET_FILE="$TARGET_DIR/image-tag.txt"
          fi
          echo "$TAG" > "$TARGET_FILE"
          if git diff --quiet --exit-code -- "$TARGET_FILE"; then
            echo "Image tag unchanged; skipping commit update."
            exit 0
          fi
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add "$TARGET_FILE"
          git commit -m "chore(frontend): update image tag $TAG"
          git push
        # 사용한 태그를 기록 파일에 저장하고 변경 시 커밋/푸시
